server:
  port: 8301
spring:
  application:
    name: WoGua-Gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: WoGua-Auth
          uri: lb://WoGua-Auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: WoGua-Server-System
          uri: lb://WoGua-Server-System
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
